### ISSUE TITLE
Maybe it's time to update?

### ISSUE THREAD

**Issue by abix5** [yandex-cloud/crossplane-provider-yc#19]
Maybe it's time to update?

**Comment by abix5** [comment]
> It seems to me that is true, it looks like outdated project for now.

I found a new one. But there are still problems there. It's good that the terraform version has been updated to 0.103
https://github.com/tagesjump/provider-upjet-yc/tree/main

P.S.
Яндекс - прям ПОЗОР! Не ожидали, что вы не будете поддерживать такой замечательный инструмент. И до сих пор есть проблема в бакете с конфликтом ACL и GRANT параметра при последующем sync. Полгода прошло как зафиксировали и подтвердили проблему!

P.S.S
Уж хоть поставьте ссылку на версию которую поддерживают в README, а эту репу в архив засуньте. А то как-то прям стыдно за вас...

**Comment by nekr0z** [comment]
Done; more in progress.
